### ISSUE TITLE
Script does work with images with filepath containing spaces

### ISSUE THREAD

**Issue by GLLM** [scheckmedia/photils-dt#1]
Hi @scheckmedia !

I saw your post on pixls.us and thought your script was really cool ... so I installed it and attempted to use it.
But it fails in my dt ... because all my files have a path containing spaces

![image](https://user-images.githubusercontent.com/3989573/81868821-3f0fd000-9573-11ea-98ea-56da536e1966.png)

Thank you
GLLM

**Comment by scheckmedia** [comment]
Hello GLLM, thanks for the details. Can you have a look to the new version whether this solves your problem?

**Comment by GLLM** [comment]
Hey @scheckmedia 
it's working now, thanks for your reactivity :)

Closing the issue !
