### ISSUE TITLE
Extract JPEG from raw when possible

### ISSUE THREAD

**Issue by timur-davletshin** [scheckmedia/photils-dt#5]
I really like the idea of this plugin, but it is slow. I used exiftool -b -JpgFromRaw to extract JPEG from raw files and it seems to provide comparable results even with heavily processed images.

**Comment by scheckmedia** [comment]
What kind of raw format are you using? Basically, the photils-cli extracts the exif of the raw file. Only if this step fails, the plugins exports an image for the classification.

**Comment by timur-davletshin** [comment]
I assumed it doesn't... maybe because I used PEFs. But anyway they have built-in JPEGs inside.

**Comment by scheckmedia** [comment]
You were right, for some reason I've disabled the call and it exports all the time the jpeg. If you want you can try to change the flag from true to false in the line: https://github.com/scheckmedia/photils-dt/blob/master/photils.lua#L300
After these changes, the behaviour should be as I mentioned before and maybe you gain some performance improvements.

**Comment by scheckmedia** [comment]
You were right, for some reason I've disabled the call and it exports all the time the jpeg. If you want you can try to change the flag from true to false in line: https://github.com/scheckmedia/photils-dt/blob/master/photils.lua#L300
After these changes, the behavior should be as I mentioned before.

**Comment by timur-davletshin** [comment]
Thanks for your help!
